services:
  - type: web
    name: tunbet-sportsbook
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromGroup: production
      - key: SUPA_URL
        fromGroup: production
      - key: SUPA_KEY
        fromGroup: production
      - key: ORO_SEAMLESS_SECRET
        fromGroup: production
